### ISSUE TITLE
Problem with searching an artist

### ISSUE THREAD

**Issue by mateja-velickovic** [cyrilnapo/SpotifyCovers#1]
Good morning,

I write you because I use your app and I want to find my favorite artist who's Shay 😍.

Unfortunately, I didn't find her, I think there's a problem with the API of your application.

Best regards.

**Comment by cyrilnapo** [comment]
**👋🏼 Hello, thanks for your suggestion, problem has been fixed with the implementation of a new feature ! 📚**

You have now clickable suggestions when searching for an artist 🔍. 

# FEATURE EXEMPLE
![image](https://github.com/user-attachments/assets/e3870e80-b371-4035-b41f-180c06659861)
